stages:
        - Initialization_stage
        - Stylecheck_doc_stage
        - Build_and_test_release_stage
        - Build_and_test_debug_stage

create_directory_and_cmake___release:
        stage: Initialization_stage
        cache:
                key: "CacheRelease"
                paths:
                        - build/release
        image: ladbukkit/openwalnut_build_environment:latest
        script:
                - ls
                - mkdir -p build
                - cd build
                - mkdir -p release
                - cd release
                - ls
                - cmake ../../src -DCMAKE_BUILD_TYPE=Release
                - ls
                
create_directory_and_cmake___debug:
        stage: Initialization_stage
        cache:
                key: "CacheDebug"
                paths:
                        - build/debug
        image: ladbukkit/openwalnut_build_environment:latest
        script:
                - ls
                - mkdir -p build
                - cd build
                - mkdir -p debug
                - cd debug
                - ls
                - cmake ../../src -DCMAKE_BUILD_TYPE=Debug
                - ls

stylecheck_job:
        stage: Stylecheck_doc_stage
        cache:
                key: "CacheRelease"
                paths:
                        - build/release
        image: ladbukkit/openwalnut_build_environment:latest
        script:
                - pwd
                - cd build/release
                - pwd 
                - ls
                - make stylecheck -j 8

doc_job:
        stage: Stylecheck_doc_stage
        cache:
                key: "CacheDebug"
                paths:
                        - build/debug
        image: ladbukkit/openwalnut_build_environment:latest
        script:
                - doxygen --version
                - pwd
                - cd build/debug
                - pwd
                - ls
                - make doc

buildAndTest:
        stage: Build_and_test_release_stage
        cache:
                key: "CacheRelease"
                paths:
                        - build/release
        image: ladbukkit/openwalnut_build_environment:latest
        script:
                - pwd
                - cd build/release
                - pwd
                - ls
                - make -j 8
                - make vtest
                
buildAndTestDebug:
        stage: Build_and_test_debug_stage
        cache:
                key: "CacheDebug"
                paths:
                        - build/debug
        image: ladbukkit/openwalnut_build_environment:latest
        script:
                - pwd
                - cd build/debug
                - pwd
                - ls
                - make -j 8
                - make vtest
