stages:
        - test

buildAndTest:
        stage: test
        script:
                mkdir build
                cmake --build build -DCMAKE_BUILD_TYPE=Release
                cmake --build build --target vtest
                cmake --build build --target stylecheck
                cmake --build build --target doc
