stages:
        - test

buildAndTest:
        stage: test
        script:
                - mkdir -p build
                - cd build
                - cmake .. -DCMAKE_BUILD_TYPE=Release
                - make vtest
                - make stylecheck
                - make doc
