stages:
        - initialJobs
        - stylecheck_doc
        - test
        - testDebug

init1:
        stage: initialJobs
        cache:
                key: "CacheRelease"
                paths:
                        - build/release
        script:
                - echo "Init1 job output"
                - ls
                - mkdir -p build
                - cd build
                - mkdir -p release
                - cd release
                - ls
                - cmake ../../src -DCMAKE_BUILD_TYPE=Release
                - ls

stylecheck_doc_job:
        stage: stylecheck_doc
        cache:
                key: "CacheRelease"
                paths:
                        - build/release
        script:
                - pwd
                - ls
                - mkdir -p build
                - cd build
                - ls
                - mkdir -p release
                - ls
                - cd release
                - ls
                - cmake ../../src -DCMAKE_BUILD_TYPE=Release
                - make stylecheck
                - make doc

buildAndTest:
        stage: test
        cache:
                key: "CacheRelease"
                paths:
                        - build/release
        script:
                - pwd
                - mkdir -p build
                - cd build
                - mkdir -p release
                - cd release
                - cmake ../../src -DCMAKE_BUILD_TYPE=Release
                - make -j 8
                - make vtest
                
buildAndTestDebug:
        stage: testDebug
        cache:
                key: "CacheDebug"
                paths:
                        - build/debug
        script:
                - pwd
                - mkdir -p build
                - cd build
                - mkdir -p debug
                - cd debug
                - cmake ../../src -DCMAKE_BUILD_TYPE=Debug
                - make -j 8
                - make vtest
