stages:
        - Initialization_stage
        - Stylecheck_doc_stage
        - Build_and_test_release_stage
        - Build_and_test_debug_stage

create_directory_and_cmake___release:
        stage: Initialization_stage
        cache:
                key: "CacheRelease"
                paths:
                        - build/release
        image: ubuntu:focal
        before_script:
                - >
                        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y
                        cmake
                        libboost-all-dev
                        qtdeclarative5-dev
                        qtwebengine5-dev
                        libqt5opengl5-dev
                        libopenscenegraph-dev
                        libeigen3-dev
                        libnifti-dev
                        build-essential
        script:
                - ls
                - mkdir -p build
                - cd build
                - mkdir -p release
                - cd release
                - ls
                - cmake ../../src -DCMAKE_BUILD_TYPE=Release
                - ls
                
create_directory_and_cmake___debug:
        stage: Initialization_stage
        cache:
                key: "CacheDebug"
                paths:
                        - build/debug
        image: ubuntu:focal
        before_script:
                - >
                        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y
                        cmake
                        libboost-all-dev
                        qtdeclarative5-dev
                        qtwebengine5-dev
                        libqt5opengl5-dev
                        libopenscenegraph-dev
                        libeigen3-dev
                        libnifti-dev
                        build-essential
        script:
                - ls
                - mkdir -p build
                - cd build
                - mkdir -p debug
                - cd debug
                - ls
                - cmake ../../src -DCMAKE_BUILD_TYPE=Debug
                - ls

stylecheck_job:
        stage: Stylecheck_doc_stage
        cache:
                key: "CacheRelease"
                paths:
                        - build/release
        image: ubuntu:focal
        before_script:
                - >
                        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y
                        cmake
                        libboost-all-dev
                        qtdeclarative5-dev
                        qtwebengine5-dev
                        libqt5opengl5-dev
                        libopenscenegraph-dev
                        libeigen3-dev
                        libnifti-dev
                        build-essential
        script:
                - pwd
                - cd build/release
                - pwd 
                - ls
                - make stylecheck

doc_job:
        stage: Stylecheck_doc_stage
        cache:
                key: "CacheDebug"
                paths:
                        - build/debug
        image: ubuntu:focal
        before_script:
                - >
                        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y
                        cmake
                        libboost-all-dev
                        qtdeclarative5-dev
                        qtwebengine5-dev
                        libqt5opengl5-dev
                        libopenscenegraph-dev
                        libeigen3-dev
                        libnifti-dev
                        build-essential
        script:
                - doxygen --version
                - pwd
                - cd build/debug
                - pwd
                - ls
                - make doc

buildAndTest:
        stage: Build_and_test_release_stage
        cache:
                key: "CacheRelease"
                paths:
                        - build/release
        image: ubuntu:focal
        before_script:
                - >
                        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y
                        cmake
                        libboost-all-dev
                        qtdeclarative5-dev
                        qtwebengine5-dev
                        libqt5opengl5-dev
                        libopenscenegraph-dev
                        libeigen3-dev
                        libnifti-dev
                        build-essential
        script:
                - pwd
                - cd build/release
                - pwd
                - ls
                - make -j 8
                - make vtest
                
buildAndTestDebug:
        stage: Build_and_test_debug_stage
        cache:
                key: "CacheDebug"
                paths:
                        - build/debug
        image: ubuntu:focal
        before_script:
                - >
                        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y
                        cmake
                        libboost-all-dev
                        qtdeclarative5-dev
                        qtwebengine5-dev
                        libqt5opengl5-dev
                        libopenscenegraph-dev
                        libeigen3-dev
                        libnifti-dev
                        build-essential
        script:
                - pwd
                - cd build/debug
                - pwd
                - ls
                - make -j 8
                - make vtest
