stages:
        - test

buildAndTest:
        stage: test
        cache:
                paths:
                        - build
        script:
                - mkdir -p build
                - cd build
                - cmake ../src -DCMAKE_BUILD_TYPE=Release
                - make -j 8
                - make vtest
                - make stylecheck
                - make doc
