stages:
        - Initialization_stage
        - Stylecheck_doc_stage
        - Build_and_test_release_stage
        - Build_and_test_debug_stage
        - Build_appimage_stage
        - Upload_artifacts_stage

variables:
        IMAGE_NAME: ladbukkit/openwalnut_build_environment:1.6

cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
                - build/release
                - build/debug
                - tools/AppImage/AppImageBuild
                - doc

create_directory_and_cmake___release:
        stage: Initialization_stage
        image: ${IMAGE_NAME}
        script:
                - ls
                - mkdir -p build
                - cd build
                - mkdir -p release
                - cd release
                - ls
                - cmake ../../src -DCMAKE_BUILD_TYPE=Release
                - ls
                
create_directory_and_cmake___debug:
        stage: Initialization_stage
        image: ${IMAGE_NAME}
        script:
                - ls
                - mkdir -p build
                - cd build
                - mkdir -p debug
                - cd debug
                - ls
                - cmake ../../src -DCMAKE_BUILD_TYPE=Debug
                - ls

stylecheck_job:
        stage: Stylecheck_doc_stage
        image: ${IMAGE_NAME}
        script:
                - pwd
                - cd build/release
                - pwd 
                - ls
                - make stylecheck -j 8

doc_job:
        stage: Stylecheck_doc_stage
        image: ${IMAGE_NAME}
        script:
                - doxygen --version
                - pwd
                - cd build/debug
                - pwd
                - ls
                - make doc

buildAndTest:
        stage: Build_and_test_release_stage
        image: ${IMAGE_NAME}
        script:
                - pwd
                - cd build/release
                - pwd
                - ls
                - make -j 8
                - make vtest
                
buildAndTestDebug:
        stage: Build_and_test_debug_stage
        image: ${IMAGE_NAME}
        script:
                - pwd
                - cd build/debug
                - pwd
                - ls
                - make -j 8
                - make vtest

buildAppImage:
        stage: Build_appimage_stage
        image: ${IMAGE_NAME}
        script:
                - pwd
                - cd tools/AppImage
                - pwd
                - ls
                - chmod +x appimage.sh
                - ./appimage.sh build

uploadArtifacts:
        stage: Upload_artifacts_stage
        image: ${IMAGE_NAME}
        script:
                - pwd
                - cd tools/upload
                - pwd
                - ls
                - chmod +x seafile.sh
                - ./seafile.sh
